openapi: 3.0.0
servers:
  - description: Documentation for https://meowfacts.herokuapp.com, an api for facts about cats, meow facts.
    url: https://virtserver.swaggerhub.com/whiterabbit8/meowfacts/1.0.0
info:
  description: This is a simple API to get facts, facts about cats, meow
  version: "1.0.0"
  title: MEOW
  contact:
    email: beau@beaubouchard.com
  license:
    name: MIT License
    url: 'https://github.com/wh-iterabb-it/meowfacts/blob/master/LICENSE'
tags:
  - name: public
    description: Operations available to the public
paths:
  /:
    get:
      tags:
        - public
      summary: get a fact about cats, a meow fact
      operationId: queryFacts
      description: |
        By passing in the appropriate options, you can recieve a specific or more than one fact.
      parameters:
        - in: query
          name: factID
          description: pass an optional id to call a specific fact
          required: false
          schema:
            type: string
        - in: query
          name: count
          description: number of facts to return
          schema:
            type: integer
            format: int32
            minimum: 1
      responses:
        '200':
          description: You just got some meowfacts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/fact'
        '400':
          description: bad input parameter
components:
  schemas:
    fact:
      type: object
      properties:
        data:
          type: array
          items:
            type: string
            example: "In ancient Egypt, killing a cat was a crime punishable by death."
