name: Default Node CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: lints
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 16 Environment . . .
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Build Docker Image "wh-iterabb-it/meowfacts"
        run: docker build -t wh-iterabb-it/meowfacts .
      - name: Run The Lints . . .
        run: docker run wh-iterabb-it/meowfacts npm run test:lint
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 16 Environment . . .
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Build Docker Image "wh-iterabb-it/meowfacts"
        run: docker build -t wh-iterabb-it/meowfacts .
      - name: Run The Tests . . .
        run: docker run wh-iterabb-it/meowfacts npm run test

